#!/bin/bash
# Negative type-checking tests. These assert diagnostics for programs that
# should be rejected by the checker even though code emission is still lenient.
set -e

WEFT=${WEFT:-./weft}
PASS=0
FAIL=0
ERRORS=""

echo "=== Negative Test Suite ==="
echo ""

check_rejects() {
  local name="$1"
  local file="$2"
  local pattern="$3"
  local out

  out=$(timeout 30 "$WEFT" check < "$file" 2>&1 >/dev/null || true)
  if echo "$out" | grep -q "$pattern"; then
    echo "  ✓ $name"
    PASS=$((PASS+1))
  else
    echo "  ✗ $name"
    FAIL=$((FAIL+1))
    ERRORS="$ERRORS\n  $name: expected diagnostic '$pattern'"
  fi
}

check_rejects "par_map_effectful" "test/negative/par_map_effectful.weft" "type error: argument type mismatch"
check_rejects "par_map_scoped_effectful" "test/negative/par_map_scoped_effectful.weft" "type error: argument type mismatch"
check_rejects "par_pool_submit_effectful" "test/negative/par_pool_submit_effectful.weft" "type error: argument type mismatch"
check_rejects "unhandled_effect_perform" "test/negative/unhandled_effect_perform.weft" "type error: effect not available in caller"
check_rejects "unhandled_alloc_effect" "test/negative/unhandled_alloc_effect.weft" "type error: effect not available in caller"
check_rejects "unsafe_raw_syscall_requires_effect" "test/negative/unsafe_raw_syscall_requires_effect.weft" "type error: effect not available in caller"
check_rejects "unsafe_raw_offset_requires_effect" "test/negative/unsafe_raw_offset_requires_effect.weft" "type error: effect not available in caller"
check_rejects "unsafe_transmute_requires_effect" "test/negative/unsafe_transmute_requires_effect.weft" "type error: effect not available in caller"
check_rejects "unsafe_int_to_ptr_requires_effect" "test/negative/unsafe_int_to_ptr_requires_effect.weft" "type error: effect not available in caller"
check_rejects "unsafe_runtime_state_requires_effect" "test/negative/unsafe_runtime_state_requires_effect.weft" "type error: effect not available in caller"
check_rejects "unsafe_set_runtime_state_requires_effect" "test/negative/unsafe_set_runtime_state_requires_effect.weft" "type error: effect not available in caller"
check_rejects "unsafe_set_handler_stack_requires_effect" "test/negative/unsafe_set_handler_stack_requires_effect.weft" "type error: effect not available in caller"
check_rejects "unsafe_raw_call_i64_requires_effect" "test/negative/unsafe_raw_call_i64_requires_effect.weft" "type error: effect not available in caller"
check_rejects "unsafe_call_closure_i64_requires_effect" "test/negative/unsafe_call_closure_i64_requires_effect.weft" "type error: effect not available in caller"
check_rejects "unsafe_got_requires_effect" "test/negative/unsafe_got_requires_effect.weft" "type error: effect not available in caller"
check_rejects "unsafe_imported_got_requires_effect" "test/negative/unsafe_imported_got_requires_effect.weft" "type error: effect not available in caller"
check_rejects "unknown_got_symbol" "test/negative/unknown_got_symbol.weft" "type error: unknown GOT symbol"
check_rejects "unknown_imported_got_symbol" "test/negative/unknown_imported_got_symbol.weft" "type error: unknown GOT symbol"
check_rejects "unsafe_wrapper_must_discharge" "test/negative/unsafe_wrapper_must_discharge.weft" "type error: effect not available in caller"
check_rejects "unsafe_raw_offset_wrapper_requires_effect" "test/negative/unsafe_raw_offset_wrapper_requires_effect.weft" "type error: effect not available in caller"
check_rejects "unsafe_transmute_wrapper_requires_effect" "test/negative/unsafe_transmute_wrapper_requires_effect.weft" "type error: effect not available in caller"
check_rejects "unsafe_int_to_ptr_wrapper_requires_effect" "test/negative/unsafe_int_to_ptr_wrapper_requires_effect.weft" "type error: effect not available in caller"
check_rejects "unsafe_runtime_state_wrapper_requires_effect" "test/negative/unsafe_runtime_state_wrapper_requires_effect.weft" "type error: effect not available in caller"
check_rejects "unsafe_process_run_command_requires_effect" "test/negative/unsafe_process_run_command_requires_effect.weft" "type error: effect not available in caller"
check_rejects "unsafe_method_call_requires_effect" "test/negative/unsafe_method_call_requires_effect.weft" "type error: effect not available in caller"
check_rejects "unsafe_lambda_to_pure_fn" "test/negative/unsafe_lambda_to_pure_fn.weft" "type error: effect not available in caller"
check_rejects "non_unsafe_handler_raw_call" "test/negative/non_unsafe_handler_raw_call.weft" "type error: effect not available in caller"
check_rejects "unhandled_effect_in_while" "test/negative/unhandled_effect_in_while.weft" "type error: effect not available in caller"
check_rejects "unhandled_effect_in_defer" "test/negative/unhandled_effect_in_defer.weft" "type error: effect not available in caller"
check_rejects "unhandled_try_effect" "test/negative/unhandled_try_effect.weft" "type error: effect not available in caller"
check_rejects "unhandled_optional_chain_effect" "test/negative/unhandled_optional_chain_effect.weft" "type error: effect not available in caller"
check_rejects "effect_perform_arg_mismatch" "test/negative/effect_perform_arg_mismatch.weft" "type error: argument type mismatch"
check_rejects "effectful_lambda_to_pure_fn" "test/negative/effectful_lambda_to_pure_fn.weft" "type error: effect not available in caller"
check_rejects "fusion_effectful_map_callback" "test/negative/fusion_effectful_map_callback.weft" "type error: effect not available in caller"
check_rejects "fusion_effectful_filter_callback" "test/negative/fusion_effectful_filter_callback.weft" "type error: effect not available in caller"
check_rejects "fusion_alloc_effect_callback" "test/negative/fusion_alloc_effect_callback.weft" "type error: argument type mismatch"
check_rejects "effectful_lambda_to_pure_effect_op" "test/negative/effectful_lambda_to_pure_effect_op.weft" "type error: effect not available in caller"
check_rejects "function_value_effect_unavailable" "test/negative/function_value_effect_unavailable.weft" "type error: effect not available in caller"
check_rejects "function_value_arg_mismatch" "test/negative/function_value_arg_mismatch.weft" "type error: argument type mismatch"
check_rejects "function_value_return_mismatch" "test/negative/function_value_return_mismatch.weft" "type error: return type mismatch"
check_rejects "method_call_arity_too_few" "test/negative/method_call_arity_too_few.weft" "type error: arity mismatch"
check_rejects "method_call_arity_too_many" "test/negative/method_call_arity_too_many.weft" "type error: arity mismatch"
check_rejects "method_call_arg_mismatch" "test/negative/method_call_arg_mismatch.weft" "type error: argument type mismatch"
check_rejects "method_call_trait_arg_mismatch" "test/negative/method_call_trait_arg_mismatch.weft" "type error: argument type mismatch"
check_rejects "method_call_effect_unavailable" "test/negative/method_call_effect_unavailable.weft" "type error: effect not available in caller"
check_rejects "method_call_unknown" "test/negative/method_call_unknown.weft" "type error: unknown method"
check_rejects "method_call_trait_unknown" "test/negative/method_call_trait_unknown.weft" "type error: unknown method"
check_rejects "trait_impl_missing_method" "test/negative/trait_impl_missing_method.weft" "type error: impl missing required method"
check_rejects "trait_impl_arity_mismatch" "test/negative/trait_impl_arity_mismatch.weft" "type error: impl method arity mismatch"
check_rejects "trait_impl_param_mismatch" "test/negative/trait_impl_param_mismatch.weft" "type error: impl method parameter type mismatch"
check_rejects "trait_impl_return_mismatch" "test/negative/trait_impl_return_mismatch.weft" "type error: impl method return type mismatch"
check_rejects "trait_impl_effect_mismatch" "test/negative/trait_impl_effect_mismatch.weft" "type error: impl method effect mismatch"
check_rejects "trait_assoc_missing" "test/negative/trait_assoc_missing.weft" "type error: impl missing required associated type"
check_rejects "trait_assoc_duplicate" "test/negative/trait_assoc_duplicate.weft" "type error: duplicate associated type binding"
check_rejects "trait_assoc_extra" "test/negative/trait_assoc_extra.weft" "type error: impl associated type is not declared by trait"
check_rejects "let_bound_lambda_effect_mismatch" "test/negative/let_bound_lambda_effect_mismatch.weft" "type error: argument type mismatch"
check_rejects "let_bound_lambda_record_effect_mismatch" "test/negative/let_bound_lambda_record_effect_mismatch.weft" "type error: argument type mismatch"
check_rejects "let_bound_lambda_method_effect_mismatch" "test/negative/let_bound_lambda_method_effect_mismatch.weft" "type error: argument type mismatch"
check_rejects "let_bound_lambda_effect_unavailable" "test/negative/let_bound_lambda_effect_unavailable.weft" "type error: effect not available in caller"
check_rejects "let_bound_lambda_return_mismatch" "test/negative/let_bound_lambda_return_mismatch.weft" "type error: argument type mismatch"
check_rejects "unknown_identifier" "test/negative/unknown_identifier.weft" "type error: unknown identifier"
check_rejects "unknown_function" "test/negative/unknown_function.weft" "type error: unknown function"
check_rejects "call_non_function" "test/negative/call_non_function.weft" "type error: called value is not a function"
check_rejects "no_payload_variant_not_function" "test/negative/no_payload_variant_not_function.weft" "type error: called value is not a function"
check_rejects "unknown_record_field" "test/negative/unknown_record_field.weft" "type error: unknown field"
check_rejects "field_access_non_record" "test/negative/field_access_non_record.weft" "type error: field access on non-record"
check_rejects "record_init_unknown_type" "test/negative/record_init_unknown_type.weft" "type error: unknown record type"
check_rejects "record_init_unknown_field" "test/negative/record_init_unknown_field.weft" "type error: unknown record field"
check_rejects "record_init_missing_field" "test/negative/record_init_missing_field.weft" "type error: missing record field"
check_rejects "record_init_duplicate_field" "test/negative/record_init_duplicate_field.weft" "type error: duplicate record field"
check_rejects "record_init_variant_type" "test/negative/record_init_variant_type.weft" "type error: not a record type"
check_rejects "record_init_field_type_mismatch" "test/negative/record_init_field_type_mismatch.weft" "type error: record field type mismatch"
check_rejects "record_field_access_type_mismatch" "test/negative/record_field_access_type_mismatch.weft" "type error: return type mismatch"
check_rejects "match_arm_i64_str_mismatch" "test/negative/match_arm_i64_str_mismatch.weft" "type error: match arm type mismatch"
check_rejects "match_arm_str_bool_mismatch" "test/negative/match_arm_str_bool_mismatch.weft" "type error: match arm type mismatch"
check_rejects "match_arm_record_mismatch" "test/negative/match_arm_record_mismatch.weft" "type error: match arm type mismatch"
check_rejects "match_non_exhaustive_int" "test/negative/match_non_exhaustive_int.weft" "type error: non-exhaustive match"
check_rejects "match_non_exhaustive_constructor" "test/negative/match_non_exhaustive_constructor.weft" "type error: non-exhaustive match"
check_rejects "match_duplicate_constructor" "test/negative/match_duplicate_constructor.weft" "type error: duplicate match constructor arm"
check_rejects "match_final_guarded" "test/negative/match_final_guarded.weft" "type error: non-exhaustive match"
check_rejects "pattern_literal_str_scrutinee" "test/negative/pattern_literal_str_scrutinee.weft" "type error: literal pattern does not match scrutinee"
check_rejects "pattern_unknown_constructor" "test/negative/pattern_unknown_constructor.weft" "type error: unknown constructor pattern"
check_rejects "pattern_constructor_on_i64" "test/negative/pattern_constructor_on_i64.weft" "type error: constructor pattern does not match scrutinee"
check_rejects "pattern_constructor_wrong_variant" "test/negative/pattern_constructor_wrong_variant.weft" "type error: constructor pattern does not match scrutinee"
check_rejects "pattern_constructor_arity_too_few" "test/negative/pattern_constructor_arity_too_few.weft" "type error: constructor pattern arity mismatch"
check_rejects "pattern_constructor_arity_too_many" "test/negative/pattern_constructor_arity_too_many.weft" "type error: constructor pattern arity mismatch"
check_rejects "if_condition_not_bool" "test/negative/if_condition_not_bool.weft" "type error: boolean expression is not bool"
check_rejects "while_condition_not_bool" "test/negative/while_condition_not_bool.weft" "type error: boolean expression is not bool"
check_rejects "for_iter_non_list" "test/negative/for_iter_non_list.weft" "type error: for iterator requires a Cons/Nil list"
check_rejects "not_operand_not_bool" "test/negative/not_operand_not_bool.weft" "type error: boolean expression is not bool"
check_rejects "logical_operand_not_bool" "test/negative/logical_operand_not_bool.weft" "type error: boolean expression is not bool"
check_rejects "match_guard_not_bool" "test/negative/match_guard_not_bool.weft" "type error: boolean expression is not bool"
check_rejects "operator_equality_mismatch" "test/negative/operator_equality_mismatch.weft" "type error: equality operand mismatch"
check_rejects "operator_relational_str" "test/negative/operator_relational_str.weft" "type error: comparison operand is not i64"
check_rejects "operator_bitwise_bool" "test/negative/operator_bitwise_bool.weft" "type error: bitwise operand is not i64"
check_rejects "operator_shift_bool" "test/negative/operator_shift_bool.weft" "type error: bitwise operand is not i64"
check_rejects "unhandled_effect_in_if_condition" "test/negative/unhandled_effect_in_if_condition.weft" "type error: effect not available in caller"
check_rejects "unhandled_effect_in_match_guard" "test/negative/unhandled_effect_in_match_guard.weft" "type error: effect not available in caller"
check_rejects "assignment_unknown_target" "test/negative/assignment_unknown_target.weft" "type error: unknown identifier"
check_rejects "assignment_i64_str_mismatch" "test/negative/assignment_i64_str_mismatch.weft" "type error: assignment type mismatch"
check_rejects "assignment_str_i64_mismatch" "test/negative/assignment_str_i64_mismatch.weft" "type error: assignment type mismatch"
check_rejects "assignment_bool_i64_mismatch" "test/negative/assignment_bool_i64_mismatch.weft" "type error: assignment type mismatch"
check_rejects "assignment_immutable_let" "test/negative/assignment_immutable_let.weft" "type error: cannot assign to immutable binding"
check_rejects "assignment_immutable_typed_let" "test/negative/assignment_immutable_typed_let.weft" "type error: cannot assign to immutable binding"
check_rejects "assignment_param_immutable" "test/negative/assignment_param_immutable.weft" "type error: cannot assign to immutable binding"
check_rejects "assignment_pattern_binding_immutable" "test/negative/assignment_pattern_binding_immutable.weft" "type error: cannot assign to immutable binding"
check_rejects "assignment_for_range_index" "test/negative/assignment_for_range_index.weft" "type error: cannot assign to immutable binding"
check_rejects "rc_bind_non_rc" "test/negative/rc_bind_non_rc.weft" "type error: value does not match let type annotation"
check_rejects "lambda_capture_mut_binding" "test/negative/lambda_capture_mut_binding.weft" "type error: cannot capture mut binding"
check_rejects "lambda_capture_mut_assignment" "test/negative/lambda_capture_mut_assignment.weft" "type error: cannot capture mut binding"
check_rejects "return_branch_type_mismatch" "test/negative/return_branch_type_mismatch.weft" "type error: return type mismatch"
check_rejects "return_str_i64_mismatch" "test/negative/return_str_i64_mismatch.weft" "type error: return type mismatch"
check_rejects "unhandled_effect_in_return" "test/negative/unhandled_effect_in_return.weft" "type error: effect not available in caller"
check_rejects "unhandled_effect_in_break" "test/negative/unhandled_effect_in_break.weft" "type error: effect not available in caller"
check_rejects "contextual_lambda_return_stmt_mismatch" "test/negative/contextual_lambda_return_stmt_mismatch.weft" "type error: return type mismatch"
check_rejects "let_bound_lambda_return_stmt_mismatch" "test/negative/let_bound_lambda_return_stmt_mismatch.weft" "type error: return type mismatch"
check_rejects "call_arity_too_few" "test/negative/call_arity_too_few.weft" "type error: arity mismatch"
check_rejects "call_arity_too_many" "test/negative/call_arity_too_many.weft" "type error: arity mismatch"
check_rejects "generic_call_arity_mismatch" "test/negative/generic_call_arity_mismatch.weft" "type error: arity mismatch"
check_rejects "generic_call_non_generic_function" "test/negative/generic_call_non_generic_function.weft" "type error: generic call target is not generic"
check_rejects "generic_call_function_value" "test/negative/generic_call_function_value.weft" "type error: generic call target is not generic"
check_rejects "generic_call_non_generic_constructor" "test/negative/generic_call_non_generic_constructor.weft" "type error: generic call target is not generic"
check_rejects "function_value_arity_mismatch" "test/negative/function_value_arity_mismatch.weft" "type error: arity mismatch"
check_rejects "effect_perform_arity_too_few" "test/negative/effect_perform_arity_too_few.weft" "type error: arity mismatch"
check_rejects "effect_perform_arity_too_many" "test/negative/effect_perform_arity_too_many.weft" "type error: arity mismatch"
check_rejects "deferred_with_k_non_deferred" "test/negative/deferred_with_k_non_deferred.weft" "type error: handler continuation requires deferred effect operation"
check_rejects "deferred_k_capture_lambda" "test/negative/deferred_k_capture_lambda.weft" "type error: cannot capture continuation"
check_rejects "deferred_k_escape_value" "test/negative/deferred_k_escape_value.weft" "type error: continuation cannot escape"
check_rejects "deferred_k_multiple_use" "test/negative/deferred_k_multiple_use.weft" "type error: continuation used more than once"
check_rejects "deferred_k_non_tail" "test/negative/deferred_k_non_tail.weft" "type error: continuation call must be tail position"
check_rejects "deferred_k_conditional_non_tail" "test/negative/deferred_k_conditional_non_tail.weft" "type error: continuation call must be tail position"
check_rejects "deferred_k_arity" "test/negative/deferred_k_arity.weft" "type error: arity mismatch"
check_rejects "deferred_k_direct_resume" "test/negative/deferred_k_direct_resume.weft" "type error: use continuation binding instead of resume"
check_rejects "handler_clause_unknown_op" "test/negative/handler_clause_unknown_op.weft" "type error: unknown effect operation"
check_rejects "handler_clause_effect_mismatch" "test/negative/handler_clause_effect_mismatch.weft" "type error: handler clause effect mismatch"
check_rejects "handler_clause_arity_too_few" "test/negative/handler_clause_arity_too_few.weft" "type error: arity mismatch"
check_rejects "handler_clause_arity_too_many" "test/negative/handler_clause_arity_too_many.weft" "type error: arity mismatch"
check_rejects "handler_clause_param_type_mismatch" "test/negative/handler_clause_param_type_mismatch.weft" "type error: argument type mismatch"
check_rejects "handler_clause_resume_type_mismatch" "test/negative/handler_clause_resume_type_mismatch.weft" "type error: resume type mismatch"
check_rejects "handler_clause_resume_capture_lambda" "test/negative/handler_clause_resume_capture_lambda.weft" "type error: cannot capture resume"
check_rejects "handler_clause_resume_capture_nested_lambda" "test/negative/handler_clause_resume_capture_nested_lambda.weft" "type error: cannot capture resume"
check_rejects "handler_clause_duplicate" "test/negative/handler_clause_duplicate.weft" "type error: duplicate handler clause"
check_rejects "handler_clause_missing_direct" "test/negative/handler_clause_missing_direct.weft" "type error: missing handler clause"
check_rejects "handler_clause_missing_branch" "test/negative/handler_clause_missing_branch.weft" "type error: missing handler clause"
check_rejects "resume_outside_handler" "test/negative/resume_outside_handler.weft" "type error: resume outside handler clause"
check_rejects "resume_outside_handler_lambda" "test/negative/resume_outside_handler_lambda.weft" "type error: resume outside handler clause"
check_rejects "generic_type_payload_mismatch" "test/negative/generic_type_payload_mismatch.weft" "type error: argument type mismatch"
check_rejects "generic_type_return_mismatch" "test/negative/generic_type_return_mismatch.weft" "type error: value does not match let type annotation"
check_rejects "generic_type_constructor_arity" "test/negative/generic_type_constructor_arity.weft" "type error: arity mismatch"
check_rejects "generic_type_arg_count" "test/negative/generic_type_arg_count.weft" "type error: wrong number of type arguments"
check_rejects "generic_type_pattern_payload_mismatch" "test/negative/generic_type_pattern_payload_mismatch.weft" "type error: return type mismatch"

echo ""
echo "=== Negative Summary ==="
echo "$PASS passed, $FAIL failed"
if [ -n "$ERRORS" ]; then
  echo ""
  echo "Failures:"
  echo -e "$ERRORS"
fi
if [ $FAIL -gt 0 ]; then exit 1; fi
