#!/bin/bash
# Negative type-checking tests. These assert diagnostics for programs that
# should be rejected by the checker even though code emission is still lenient.
set -e

WEFT=${WEFT:-./weft}
PASS=0
FAIL=0
ERRORS=""

echo "=== Negative Test Suite ==="
echo ""

check_rejects() {
  local name="$1"
  local file="$2"
  local pattern="$3"
  local out

  out=$(timeout 30 "$WEFT" check "$file" 2>&1 >/dev/null || true)
  if echo "$out" | grep -q "$pattern"; then
    echo "  ✓ $name"
    PASS=$((PASS+1))
  else
    echo "  ✗ $name"
    FAIL=$((FAIL+1))
    ERRORS="$ERRORS\n  $name: expected diagnostic '$pattern'"
  fi
}

check_rejects "par_map_effectful" "test/negative/par_map_effectful.weft" "type error: argument type mismatch"
check_rejects "par_map_scoped_effectful" "test/negative/par_map_scoped_effectful.weft" "type error: argument type mismatch"
check_rejects "par_pool_submit_effectful" "test/negative/par_pool_submit_effectful.weft" "type error: argument type mismatch"
check_rejects "generator_new_non_literal_producer" "test/negative/generator_new_non_literal_producer.weft" "type error: generator producer must be literal zero-arg lambda, known zero-arg function, or known zero-arg closure"
check_rejects "generator_new_nonzero_arg_producer" "test/negative/generator_new_nonzero_arg_producer.weft" "type error: generator producer must be literal zero-arg lambda, known zero-arg function, or known zero-arg closure"
check_rejects "generator_new_function_with_arg" "test/negative/generator_new_function_with_arg.weft" "type error: generator producer must be literal zero-arg lambda, known zero-arg function, or known zero-arg closure"
check_rejects "generator_new_mutable_closure_producer" "test/negative/generator_new_mutable_closure_producer.weft" "type error: generator producer must be literal zero-arg lambda, known zero-arg function, or known zero-arg closure"
check_rejects "generator_new_return_type_mismatch" "test/negative/generator_new_return_type_mismatch.weft" "type error: return type mismatch"
check_rejects "generator_yield_unhandled" "test/negative/generator_yield_unhandled.weft" "type error: effect not available in caller"
check_rejects "generator_generic_new_non_literal_producer" "test/negative/generator_generic_new_non_literal_producer.weft" "type error: generator producer must be literal zero-arg lambda, known zero-arg function, or known zero-arg closure"
check_rejects "generator_generic_new_function_with_arg" "test/negative/generator_generic_new_function_with_arg.weft" "type error: generator producer must be literal zero-arg lambda, known zero-arg function, or known zero-arg closure"
check_rejects "generator_generic_new_mutable_closure_producer" "test/negative/generator_generic_new_mutable_closure_producer.weft" "type error: generator producer must be literal zero-arg lambda, known zero-arg function, or known zero-arg closure"
check_rejects "generator_generic_new_return_type_mismatch" "test/negative/generator_generic_new_return_type_mismatch.weft" "type error: return type mismatch"
check_rejects "generator_generic_yield_unhandled" "test/negative/generator_generic_yield_unhandled.weft" "type error: effect not available in caller"
check_rejects "unhandled_effect_perform" "test/negative/unhandled_effect_perform.weft" "type error: effect not available in caller"
check_rejects "unhandled_alloc_effect" "test/negative/unhandled_alloc_effect.weft" "type error: effect not available in caller"
check_rejects "unsafe_raw_syscall_requires_effect" "test/negative/unsafe_raw_syscall_requires_effect.weft" "type error: effect not available in caller"
check_rejects "unsafe_raw_offset_requires_effect" "test/negative/unsafe_raw_offset_requires_effect.weft" "type error: effect not available in caller"
check_rejects "unsafe_transmute_requires_effect" "test/negative/unsafe_transmute_requires_effect.weft" "type error: effect not available in caller"
check_rejects "unsafe_int_to_ptr_requires_effect" "test/negative/unsafe_int_to_ptr_requires_effect.weft" "type error: effect not available in caller"
check_rejects "unsafe_runtime_state_requires_effect" "test/negative/unsafe_runtime_state_requires_effect.weft" "type error: effect not available in caller"
check_rejects "unsafe_set_runtime_state_requires_effect" "test/negative/unsafe_set_runtime_state_requires_effect.weft" "type error: effect not available in caller"
check_rejects "unsafe_set_handler_stack_requires_effect" "test/negative/unsafe_set_handler_stack_requires_effect.weft" "type error: effect not available in caller"
check_rejects "unsafe_raw_call_i64_requires_effect" "test/negative/unsafe_raw_call_i64_requires_effect.weft" "type error: effect not available in caller"
check_rejects "unsafe_call_closure_i64_requires_effect" "test/negative/unsafe_call_closure_i64_requires_effect.weft" "type error: effect not available in caller"
check_rejects "unsafe_fiber_suspend_requires_effect" "test/negative/unsafe_fiber_suspend_requires_effect.weft" "type error: effect not available in caller"
check_rejects "unsafe_fiber_resume_requires_effect" "test/negative/unsafe_fiber_resume_requires_effect.weft" "type error: effect not available in caller"
check_rejects "unsafe_fiber_wrapper_requires_effect" "test/negative/unsafe_fiber_wrapper_requires_effect.weft" "type error: effect not available in caller"
check_rejects "unsafe_got_requires_effect" "test/negative/unsafe_got_requires_effect.weft" "type error: effect not available in caller"
check_rejects "root_raw_syscall_with_effect_requires_trusted" "test/negative/root_raw_syscall_with_effect_requires_trusted.weft" "type error: Unsafe is sealed to trusted runtime/platform code"
check_rejects "root_mem_with_effect_requires_trusted" "test/negative/root_mem_with_effect_requires_trusted.weft" "type error: Unsafe is sealed to trusted runtime/platform code"
check_rejects "root_alloc_with_effect_requires_trusted" "test/negative/root_alloc_with_effect_requires_trusted.weft" "type error: raw allocation is sealed to trusted runtime/platform code"
check_rejects "root_pointer_with_effect_requires_trusted" "test/negative/root_pointer_with_effect_requires_trusted.weft" "type error: Unsafe is sealed to trusted runtime/platform code"
check_rejects "root_unsafe_handler_requires_trusted" "test/negative/root_unsafe_handler_requires_trusted.weft" "type error: Unsafe is sealed to trusted runtime/platform code"
check_rejects "root_unsafe_perform_requires_trusted" "test/negative/root_unsafe_perform_requires_trusted.weft" "type error: Unsafe is sealed to trusted runtime/platform code"
check_rejects "pipeline_origin_helper_requires_trusted" "test/negative/pipeline_origin_helper_requires_trusted.weft" "type error: source trust is sealed to trusted compiler/runtime code"
check_rejects "pipeline_trust_helper_requires_trusted" "test/negative/pipeline_trust_helper_requires_trusted.weft" "type error: source trust is sealed to trusted compiler/runtime code"
check_rejects "ttable_mark_trusted_requires_trusted" "test/negative/ttable_mark_trusted_requires_trusted.weft" "type error: source trust is sealed to trusted compiler/runtime code"
check_rejects "unsafe_imported_got_requires_trusted" "test/negative/unsafe_imported_got_requires_effect.weft" "type error: Unsafe is sealed to trusted runtime/platform code"
check_rejects "unsafe_imported_mem_requires_trusted" "test/negative/unsafe_imported_mem_requires_effect.weft" "type error: Unsafe is sealed to trusted runtime/platform code"
check_rejects "unsafe_imported_mem_store_requires_trusted" "test/negative/unsafe_imported_mem_store_requires_effect.weft" "type error: Unsafe is sealed to trusted runtime/platform code"
check_rejects "unsafe_imported_got_with_effect_requires_trusted" "test/negative/unsafe_imported_got_with_effect_requires_trusted.weft" "type error: Unsafe is sealed to trusted runtime/platform code"
check_rejects "unsafe_imported_mem_with_effect_requires_trusted" "test/negative/unsafe_imported_mem_with_effect_requires_trusted.weft" "type error: Unsafe is sealed to trusted runtime/platform code"
check_rejects "unsafe_imported_mem_store_with_effect_requires_trusted" "test/negative/unsafe_imported_mem_store_with_effect_requires_trusted.weft" "type error: Unsafe is sealed to trusted runtime/platform code"
check_rejects "imported_bump_alloc_requires_trusted" "test/negative/imported_bump_alloc_requires_trusted.weft" "type error: raw allocation is sealed to trusted runtime/platform code"
check_rejects "imported_alloc_bump_with_effect_requires_trusted" "test/negative/imported_alloc_bump_with_effect_requires_trusted.weft" "type error: raw allocation is sealed to trusted runtime/platform code"
check_rejects "unsafe_imported_handler_requires_trusted" "test/negative/unsafe_imported_handler_requires_trusted.weft" "type error: Unsafe is sealed to trusted runtime/platform code"
check_rejects "unsafe_imported_perform_requires_trusted" "test/negative/unsafe_imported_perform_requires_trusted.weft" "type error: Unsafe is sealed to trusted runtime/platform code"
check_rejects "unknown_got_symbol" "test/negative/unknown_got_symbol.weft" "type error: unknown GOT symbol"
check_rejects "unknown_imported_got_symbol" "test/negative/unknown_imported_got_symbol.weft" "type error: unknown GOT symbol"
check_rejects "unsafe_wrapper_must_discharge" "test/negative/unsafe_wrapper_must_discharge.weft" "type error: effect not available in caller"
check_rejects "unsafe_raw_offset_wrapper_requires_effect" "test/negative/unsafe_raw_offset_wrapper_requires_effect.weft" "type error: effect not available in caller"
check_rejects "unsafe_transmute_wrapper_requires_effect" "test/negative/unsafe_transmute_wrapper_requires_effect.weft" "type error: effect not available in caller"
check_rejects "unsafe_int_to_ptr_wrapper_requires_effect" "test/negative/unsafe_int_to_ptr_wrapper_requires_effect.weft" "type error: effect not available in caller"
check_rejects "unsafe_raw_offset_pointer_arg_required" "test/negative/unsafe_raw_offset_pointer_arg_required.weft" "type error: argument type mismatch"
check_rejects "unsafe_raw_offset_wrapper_pointer_arg_required" "test/negative/unsafe_raw_offset_wrapper_pointer_arg_required.weft" "type error: argument type mismatch"
check_rejects "unsafe_int_to_ptr_addr_mismatch" "test/negative/unsafe_int_to_ptr_addr_mismatch.weft" "type error: argument type mismatch"
check_rejects "unsafe_transmute_arity_mismatch" "test/negative/unsafe_transmute_arity_mismatch.weft" "type error: arity mismatch"
check_rejects "unsafe_runtime_state_wrapper_requires_effect" "test/negative/unsafe_runtime_state_wrapper_requires_effect.weft" "type error: effect not available in caller"
check_rejects "unsafe_process_run_command_requires_effect" "test/negative/unsafe_process_run_command_requires_effect.weft" "type error: effect not available in caller"
check_rejects "unsafe_method_call_requires_effect" "test/negative/unsafe_method_call_requires_effect.weft" "type error: effect not available in caller"
check_rejects "unsafe_lambda_to_pure_fn" "test/negative/unsafe_lambda_to_pure_fn.weft" "type error: effect not available in caller"
check_rejects "non_unsafe_handler_raw_call" "test/negative/non_unsafe_handler_raw_call.weft" "type error: effect not available in caller"
check_rejects "unhandled_effect_in_while" "test/negative/unhandled_effect_in_while.weft" "type error: effect not available in caller"
check_rejects "unhandled_effect_in_defer" "test/negative/unhandled_effect_in_defer.weft" "type error: effect not available in caller"
check_rejects "unhandled_try_effect" "test/negative/unhandled_try_effect.weft" "type error: effect not available in caller"
check_rejects "unhandled_optional_chain_effect" "test/negative/unhandled_optional_chain_effect.weft" "type error: effect not available in caller"
check_rejects "effect_perform_arg_mismatch" "test/negative/effect_perform_arg_mismatch.weft" "type error: argument type mismatch"
check_rejects "effectful_lambda_to_pure_fn" "test/negative/effectful_lambda_to_pure_fn.weft" "type error: effect not available in caller"
check_rejects "fusion_effectful_map_callback" "test/negative/fusion_effectful_map_callback.weft" "type error: effect not available in caller"
check_rejects "fusion_effectful_filter_callback" "test/negative/fusion_effectful_filter_callback.weft" "type error: effect not available in caller"
check_rejects "fusion_alloc_effect_callback" "test/negative/fusion_alloc_effect_callback.weft" "type error: argument type mismatch"
check_rejects "iter_fold_effectful_callback" "test/negative/iter_fold_effectful_callback.weft" "type error: effect not available in caller"
check_rejects "iter_map_collect_effectful_callback" "test/negative/iter_map_collect_effectful_callback.weft" "type error: effect not available in caller"
check_rejects "iter_map_effectful_callback" "test/negative/iter_map_effectful_callback.weft" "type error: effect not available in caller"
check_rejects "iter_filter_effectful_callback" "test/negative/iter_filter_effectful_callback.weft" "type error: effect not available in caller"
check_rejects "effectful_lambda_to_pure_effect_op" "test/negative/effectful_lambda_to_pure_effect_op.weft" "type error: effect not available in caller"
check_rejects "function_value_effect_unavailable" "test/negative/function_value_effect_unavailable.weft" "type error: effect not available in caller"
check_rejects "function_value_arg_mismatch" "test/negative/function_value_arg_mismatch.weft" "type error: argument type mismatch"
check_rejects "function_value_return_mismatch" "test/negative/function_value_return_mismatch.weft" "type error: return type mismatch"
check_rejects "method_call_arity_too_few" "test/negative/method_call_arity_too_few.weft" "type error: arity mismatch"
check_rejects "method_call_arity_too_many" "test/negative/method_call_arity_too_many.weft" "type error: arity mismatch"
check_rejects "method_call_arg_mismatch" "test/negative/method_call_arg_mismatch.weft" "type error: argument type mismatch"
check_rejects "method_call_trait_arg_mismatch" "test/negative/method_call_trait_arg_mismatch.weft" "type error: argument type mismatch"
check_rejects "method_call_effect_unavailable" "test/negative/method_call_effect_unavailable.weft" "type error: effect not available in caller"
check_rejects "method_call_unknown" "test/negative/method_call_unknown.weft" "type error: unknown method"
check_rejects "method_call_trait_unknown" "test/negative/method_call_trait_unknown.weft" "type error: unknown method"
check_rejects "trait_impl_missing_method" "test/negative/trait_impl_missing_method.weft" "type error: impl missing required method"
check_rejects "trait_impl_arity_mismatch" "test/negative/trait_impl_arity_mismatch.weft" "type error: impl method arity mismatch"
check_rejects "trait_impl_param_mismatch" "test/negative/trait_impl_param_mismatch.weft" "type error: impl method parameter type mismatch"
check_rejects "trait_impl_return_mismatch" "test/negative/trait_impl_return_mismatch.weft" "type error: impl method return type mismatch"
check_rejects "trait_impl_effect_mismatch" "test/negative/trait_impl_effect_mismatch.weft" "type error: impl method effect mismatch"
check_rejects "trait_assoc_missing" "test/negative/trait_assoc_missing.weft" "type error: impl missing required associated type"
check_rejects "trait_assoc_duplicate" "test/negative/trait_assoc_duplicate.weft" "type error: duplicate associated type binding"
check_rejects "trait_assoc_extra" "test/negative/trait_assoc_extra.weft" "type error: impl associated type is not declared by trait"
check_rejects "trait_impl_conflict" "test/negative/trait_impl_conflict.weft" "type error: conflicting implementations of trait for type"
check_rejects "let_bound_lambda_effect_mismatch" "test/negative/let_bound_lambda_effect_mismatch.weft" "type error: argument type mismatch"
check_rejects "let_bound_lambda_record_effect_mismatch" "test/negative/let_bound_lambda_record_effect_mismatch.weft" "type error: argument type mismatch"
check_rejects "let_bound_lambda_method_effect_mismatch" "test/negative/let_bound_lambda_method_effect_mismatch.weft" "type error: argument type mismatch"
check_rejects "let_bound_lambda_effect_unavailable" "test/negative/let_bound_lambda_effect_unavailable.weft" "type error: effect not available in caller"
check_rejects "let_bound_lambda_return_mismatch" "test/negative/let_bound_lambda_return_mismatch.weft" "type error: argument type mismatch"
check_rejects "unknown_identifier" "test/negative/unknown_identifier.weft" "type error: unknown identifier"
check_rejects "unknown_function" "test/negative/unknown_function.weft" "type error: unknown function"
check_rejects "call_non_function" "test/negative/call_non_function.weft" "type error: called value is not a function"
check_rejects "no_payload_variant_not_function" "test/negative/no_payload_variant_not_function.weft" "type error: called value is not a function"
check_rejects "unknown_record_field" "test/negative/unknown_record_field.weft" "type error: unknown field"
check_rejects "field_access_non_record" "test/negative/field_access_non_record.weft" "type error: field access on non-record"
check_rejects "record_init_unknown_type" "test/negative/record_init_unknown_type.weft" "type error: unknown record type"
check_rejects "record_init_unknown_field" "test/negative/record_init_unknown_field.weft" "type error: unknown record field"
check_rejects "record_init_missing_field" "test/negative/record_init_missing_field.weft" "type error: missing record field"
check_rejects "record_init_duplicate_field" "test/negative/record_init_duplicate_field.weft" "type error: duplicate record field"
check_rejects "record_init_variant_type" "test/negative/record_init_variant_type.weft" "type error: not a record type"
check_rejects "record_init_field_type_mismatch" "test/negative/record_init_field_type_mismatch.weft" "type error: record field type mismatch"
check_rejects "record_field_access_type_mismatch" "test/negative/record_field_access_type_mismatch.weft" "type error: return type mismatch"
check_rejects "match_arm_i64_str_mismatch" "test/negative/match_arm_i64_str_mismatch.weft" "type error: match arm type mismatch"
check_rejects "match_arm_str_bool_mismatch" "test/negative/match_arm_str_bool_mismatch.weft" "type error: match arm type mismatch"
check_rejects "match_arm_record_mismatch" "test/negative/match_arm_record_mismatch.weft" "type error: match arm type mismatch"
check_rejects "match_non_exhaustive_int" "test/negative/match_non_exhaustive_int.weft" "type error: non-exhaustive match"
check_rejects "match_non_exhaustive_constructor" "test/negative/match_non_exhaustive_constructor.weft" "type error: non-exhaustive match"
check_rejects "match_duplicate_constructor" "test/negative/match_duplicate_constructor.weft" "type error: duplicate match constructor arm"
check_rejects "match_final_guarded" "test/negative/match_final_guarded.weft" "type error: non-exhaustive match"
check_rejects "pattern_literal_str_scrutinee" "test/negative/pattern_literal_str_scrutinee.weft" "type error: literal pattern does not match scrutinee"
check_rejects "pattern_unknown_constructor" "test/negative/pattern_unknown_constructor.weft" "type error: unknown constructor pattern"
check_rejects "pattern_constructor_on_i64" "test/negative/pattern_constructor_on_i64.weft" "type error: constructor pattern does not match scrutinee"
check_rejects "pattern_constructor_wrong_variant" "test/negative/pattern_constructor_wrong_variant.weft" "type error: constructor pattern does not match scrutinee"
check_rejects "pattern_constructor_arity_too_few" "test/negative/pattern_constructor_arity_too_few.weft" "type error: constructor pattern arity mismatch"
check_rejects "pattern_constructor_arity_too_many" "test/negative/pattern_constructor_arity_too_many.weft" "type error: constructor pattern arity mismatch"
check_rejects "if_condition_not_bool" "test/negative/if_condition_not_bool.weft" "type error: boolean expression is not bool"
check_rejects "while_condition_not_bool" "test/negative/while_condition_not_bool.weft" "type error: boolean expression is not bool"
check_rejects "for_iter_non_list" "test/negative/for_iter_non_list.weft" "type error: for iterator requires a Cons/Nil list"
check_rejects "not_operand_not_bool" "test/negative/not_operand_not_bool.weft" "type error: boolean expression is not bool"
check_rejects "logical_operand_not_bool" "test/negative/logical_operand_not_bool.weft" "type error: boolean expression is not bool"
check_rejects "match_guard_not_bool" "test/negative/match_guard_not_bool.weft" "type error: boolean expression is not bool"
check_rejects "operator_equality_mismatch" "test/negative/operator_equality_mismatch.weft" "type error: equality operand mismatch"
check_rejects "operator_relational_str" "test/negative/operator_relational_str.weft" "type error: comparison operand is not i64"
check_rejects "operator_bitwise_bool" "test/negative/operator_bitwise_bool.weft" "type error: bitwise operand is not i64"
check_rejects "operator_shift_bool" "test/negative/operator_shift_bool.weft" "type error: bitwise operand is not i64"
check_rejects "f64_i64_arithmetic_mismatch" "test/negative/f64_i64_arithmetic_mismatch.weft" "type error: arithmetic operand type mismatch"
check_rejects "f64_i64_comparison_mismatch" "test/negative/f64_i64_comparison_mismatch.weft" "type error: comparison operand type mismatch"
check_rejects "f64_bitwise" "test/negative/f64_bitwise.weft" "type error: bitwise operand is not i64"
check_rejects "f64_modulo" "test/negative/f64_modulo.weft" "type error: arithmetic operand is not i64"
check_rejects "f32_f64_arithmetic_mismatch" "test/negative/f32_f64_arithmetic_mismatch.weft" "type error: arithmetic operand type mismatch"
check_rejects "f32_i64_arithmetic_mismatch" "test/negative/f32_i64_arithmetic_mismatch.weft" "type error: arithmetic operand type mismatch"
check_rejects "f32_f64_comparison_mismatch" "test/negative/f32_f64_comparison_mismatch.weft" "type error: comparison operand type mismatch"
check_rejects "f32_f64_assignment_mismatch" "test/negative/f32_f64_assignment_mismatch.weft" "type error: value does not match let type annotation"
check_rejects "f32_bitwise" "test/negative/f32_bitwise.weft" "type error: bitwise operand is not i64"
check_rejects "f32_call_f64_arg_mismatch" "test/negative/f32_call_f64_arg_mismatch.weft" "type error: argument type mismatch"
check_rejects "i32_i64_arithmetic_mismatch" "test/negative/i32_i64_arithmetic_mismatch.weft" "type error: arithmetic operand type mismatch"
check_rejects "i32_literal_out_of_range" "test/negative/i32_literal_out_of_range.weft" "type error: value does not match let type annotation"
check_rejects "i64_positive_literal_out_of_range" "test/negative/i64_positive_literal_out_of_range.weft" "type error: value does not match let type annotation"
check_rejects "untyped_integer_literal_out_of_range" "test/negative/untyped_integer_literal_out_of_range.weft" "type error: integer literal out of range"
check_rejects "i32_i64_assignment_mismatch" "test/negative/i32_i64_assignment_mismatch.weft" "type error: value does not match let type annotation"
check_rejects "i32_call_i64_arg_mismatch" "test/negative/i32_call_i64_arg_mismatch.weft" "type error: argument type mismatch"
check_rejects "i8_literal_out_of_range" "test/negative/i8_literal_out_of_range.weft" "type error: value does not match let type annotation"
check_rejects "u8_negative_literal" "test/negative/u8_negative_literal.weft" "type error: value does not match let type annotation"
check_rejects "u64_literal_out_of_range" "test/negative/u64_literal_out_of_range.weft" "type error: value does not match let type annotation"
check_rejects "u64_return_literal_out_of_range" "test/negative/u64_return_literal_out_of_range.weft" "type error: return type mismatch"
check_rejects "u64_negative_literal" "test/negative/u64_negative_literal.weft" "type error: value does not match let type annotation"
check_rejects "u64_pattern_literal_out_of_range" "test/negative/u64_pattern_literal_out_of_range.weft" "type error: literal pattern does not match scrutinee"
check_rejects "u8_i8_arithmetic_mismatch" "test/negative/u8_i8_arithmetic_mismatch.weft" "type error: arithmetic operand type mismatch"
check_rejects "u32_i32_comparison_mismatch" "test/negative/u32_i32_comparison_mismatch.weft" "type error: comparison operand type mismatch"
check_rejects "usize_i64_assignment_mismatch" "test/negative/usize_i64_assignment_mismatch.weft" "type error: value does not match let type annotation"
check_rejects "u8_call_i64_arg_mismatch" "test/negative/u8_call_i64_arg_mismatch.weft" "type error: argument type mismatch"
check_rejects "num_i64_to_f64_arg_mismatch" "test/negative/num_i64_to_f64_arg_mismatch.weft" "type error: argument type mismatch"
check_rejects "intrinsic_i64_to_f64_arg_mismatch" "test/negative/intrinsic_i64_to_f64_arg_mismatch.weft" "type error: argument type mismatch"
check_rejects "num_u32_to_f64_arg_mismatch" "test/negative/num_u32_to_f64_arg_mismatch.weft" "type error: argument type mismatch"
check_rejects "intrinsic_u64_to_f64_arg_mismatch" "test/negative/intrinsic_u64_to_f64_arg_mismatch.weft" "type error: argument type mismatch"
check_rejects "num_f64_to_i64_exact_arg_mismatch" "test/negative/num_f64_to_i64_exact_arg_mismatch.weft" "type error: argument type mismatch"
check_rejects "intrinsic_f64_to_i64_arg_mismatch" "test/negative/intrinsic_f64_to_i64_arg_mismatch.weft" "type error: argument type mismatch"
check_rejects "num_f32_to_f64_arg_mismatch" "test/negative/num_f32_to_f64_arg_mismatch.weft" "type error: argument type mismatch"
check_rejects "num_f64_to_f32_round_arg_mismatch" "test/negative/num_f64_to_f32_round_arg_mismatch.weft" "type error: argument type mismatch"
check_rejects "num_i32_to_f32_round_arg_mismatch" "test/negative/num_i32_to_f32_round_arg_mismatch.weft" "type error: argument type mismatch"
check_rejects "intrinsic_f32_to_f64_arg_mismatch" "test/negative/intrinsic_f32_to_f64_arg_mismatch.weft" "type error: argument type mismatch"
check_rejects "intrinsic_f64_to_f32_arg_mismatch" "test/negative/intrinsic_f64_to_f32_arg_mismatch.weft" "type error: argument type mismatch"
check_rejects "intrinsic_i16_to_f32_arg_mismatch" "test/negative/intrinsic_i16_to_f32_arg_mismatch.weft" "type error: argument type mismatch"
check_rejects "math_sqrt_f64_arg_mismatch" "test/negative/math_sqrt_f64_arg_mismatch.weft" "type error: argument type mismatch"
check_rejects "math_sqrt_f32_arg_mismatch" "test/negative/math_sqrt_f32_arg_mismatch.weft" "type error: argument type mismatch"
check_rejects "intrinsic_f64_sqrt_arg_mismatch" "test/negative/intrinsic_f64_sqrt_arg_mismatch.weft" "type error: argument type mismatch"
check_rejects "intrinsic_f32_sqrt_arg_mismatch" "test/negative/intrinsic_f32_sqrt_arg_mismatch.weft" "type error: argument type mismatch"
check_rejects "num_i64_to_i8_checked_arg_mismatch" "test/negative/num_i64_to_i8_checked_arg_mismatch.weft" "type error: argument type mismatch"
check_rejects "num_int_cast_value_or_default_mismatch" "test/negative/num_int_cast_value_or_default_mismatch.weft" "type error: argument type mismatch"
check_rejects "intrinsic_i64_to_i8_arg_mismatch" "test/negative/intrinsic_i64_to_i8_arg_mismatch.weft" "type error: argument type mismatch"
check_rejects "intrinsic_u16_to_u64_arg_mismatch" "test/negative/intrinsic_u16_to_u64_arg_mismatch.weft" "type error: argument type mismatch"
check_rejects "num_trait_bool_not_numeric" "test/negative/num_trait_bool_not_numeric.weft" "type error: type does not satisfy trait bound"
check_rejects "num_trait_str_not_integer" "test/negative/num_trait_str_not_integer.weft" "type error: type does not satisfy trait bound"
check_rejects "num_trait_float_not_integer" "test/negative/num_trait_float_not_integer.weft" "type error: type does not satisfy trait bound"
check_rejects "num_trait_unsigned_not_signed" "test/negative/num_trait_unsigned_not_signed.weft" "type error: type does not satisfy trait bound"
check_rejects "num_trait_signed_not_unsigned" "test/negative/num_trait_signed_not_unsigned.weft" "type error: type does not satisfy trait bound"
check_rejects "unhandled_effect_in_if_condition" "test/negative/unhandled_effect_in_if_condition.weft" "type error: effect not available in caller"
check_rejects "unhandled_effect_in_match_guard" "test/negative/unhandled_effect_in_match_guard.weft" "type error: effect not available in caller"
check_rejects "assignment_unknown_target" "test/negative/assignment_unknown_target.weft" "type error: unknown identifier"
check_rejects "assignment_i64_str_mismatch" "test/negative/assignment_i64_str_mismatch.weft" "type error: assignment type mismatch"
check_rejects "assignment_str_i64_mismatch" "test/negative/assignment_str_i64_mismatch.weft" "type error: assignment type mismatch"
check_rejects "assignment_bool_i64_mismatch" "test/negative/assignment_bool_i64_mismatch.weft" "type error: assignment type mismatch"
check_rejects "assignment_immutable_let" "test/negative/assignment_immutable_let.weft" "type error: cannot assign to immutable binding"
check_rejects "assignment_immutable_typed_let" "test/negative/assignment_immutable_typed_let.weft" "type error: cannot assign to immutable binding"
check_rejects "assignment_param_immutable" "test/negative/assignment_param_immutable.weft" "type error: cannot assign to immutable binding"
check_rejects "assignment_pattern_binding_immutable" "test/negative/assignment_pattern_binding_immutable.weft" "type error: cannot assign to immutable binding"
check_rejects "assignment_for_range_index" "test/negative/assignment_for_range_index.weft" "type error: cannot assign to immutable binding"
check_rejects "pointer_address_requires_unsafe" "test/negative/pointer_address_requires_unsafe.weft" "type error: effect not available in caller"
check_rejects "pointer_deref_requires_unsafe" "test/negative/pointer_deref_requires_unsafe.weft" "type error: effect not available in caller"
check_rejects "pointer_assignment_requires_unsafe" "test/negative/pointer_assignment_requires_unsafe.weft" "type error: effect not available in caller"
check_rejects "imported_pointer_address_requires_trusted" "test/negative/imported_pointer_address_requires_trusted.weft" "type error: Unsafe is sealed to trusted runtime/platform code"
check_rejects "imported_pointer_deref_requires_trusted" "test/negative/imported_pointer_deref_requires_trusted.weft" "type error: Unsafe is sealed to trusted runtime/platform code"
check_rejects "imported_pointer_store_requires_trusted" "test/negative/imported_pointer_store_requires_trusted.weft" "type error: Unsafe is sealed to trusted runtime/platform code"
check_rejects "pointer_address_of_literal" "test/negative/pointer_address_of_literal.weft" "type error: address-of target must be a binding"
check_rejects "pointer_deref_non_pointer" "test/negative/pointer_deref_non_pointer.weft" "type error: dereference of non-pointer"
check_rejects "pointer_mut_address_of_immutable" "test/negative/pointer_mut_address_of_immutable.weft" "type error: cannot take mutable pointer to immutable binding"
check_rejects "pointer_value_to_param" "test/negative/pointer_value_to_param.weft" "type error: argument type mismatch"
check_rejects "pointer_assignment_immutable" "test/negative/pointer_assignment_immutable.weft" "type error: cannot write through immutable pointer"
check_rejects "pointer_assignment_type_mismatch" "test/negative/pointer_assignment_type_mismatch.weft" "type error: pointer assignment type mismatch"
check_rejects "pointer_assignment_non_pointer" "test/negative/pointer_assignment_non_pointer.weft" "type error: dereference of non-pointer"
check_rejects "rc_bind_non_rc" "test/negative/rc_bind_non_rc.weft" "type error: value does not match let type annotation"
check_rejects "ownership_cycle_vector_self" "test/negative/ownership_cycle_vector_self.weft" "type error: strong ownership cycle requires weak or id edge"
check_rejects "ownership_cycle_vector_mutual" "test/negative/ownership_cycle_vector_mutual.weft" "type error: strong ownership cycle requires weak or id edge"
check_rejects "ownership_cycle_vector_generic_box" "test/negative/ownership_cycle_vector_generic_box.weft" "type error: strong ownership cycle requires weak or id edge"
check_rejects "ownership_cycle_vector_arc" "test/negative/ownership_cycle_vector_arc.weft" "type error: strong ownership cycle requires weak or id edge"
check_rejects "ownership_cycle_vector_closure" "test/negative/ownership_cycle_vector_closure.weft" "type error: closure capture cycle requires weak or id edge"
check_rejects "ownership_cycle_vector_closure_box" "test/negative/ownership_cycle_vector_closure_box.weft" "type error: closure capture cycle requires weak or id edge"
check_rejects "ownership_cycle_vector_continuation" "test/negative/ownership_cycle_vector_continuation.weft" "type error: closure capture cycle requires weak or id edge"
check_rejects "weak_ref_unmanaged" "test/negative/weak_ref_unmanaged.weft" "type error: weak_ref requires managed value"
check_rejects "weak_load_nonweak" "test/negative/weak_load_nonweak.weft" "type error: weak_load requires weak managed reference"
check_rejects "weak_ref_arity" "test/negative/weak_ref_arity.weft" "type error: arity mismatch"
check_rejects "weak_load_nullable_required" "test/negative/weak_load_nullable_required.weft" "type error: value does not match let type annotation"
check_rejects "lambda_capture_mut_binding" "test/negative/lambda_capture_mut_binding.weft" "type error: cannot capture mut binding"
check_rejects "lambda_capture_mut_assignment" "test/negative/lambda_capture_mut_assignment.weft" "type error: cannot capture mut binding"
check_rejects "return_branch_type_mismatch" "test/negative/return_branch_type_mismatch.weft" "type error: return type mismatch"
check_rejects "return_str_i64_mismatch" "test/negative/return_str_i64_mismatch.weft" "type error: return type mismatch"
check_rejects "unhandled_effect_in_return" "test/negative/unhandled_effect_in_return.weft" "type error: effect not available in caller"
check_rejects "unhandled_effect_in_break" "test/negative/unhandled_effect_in_break.weft" "type error: effect not available in caller"
check_rejects "contextual_lambda_return_stmt_mismatch" "test/negative/contextual_lambda_return_stmt_mismatch.weft" "type error: return type mismatch"
check_rejects "let_bound_lambda_return_stmt_mismatch" "test/negative/let_bound_lambda_return_stmt_mismatch.weft" "type error: return type mismatch"
check_rejects "call_arity_too_few" "test/negative/call_arity_too_few.weft" "type error: arity mismatch"
check_rejects "call_arity_too_many" "test/negative/call_arity_too_many.weft" "type error: arity mismatch"
check_rejects "generic_call_arity_mismatch" "test/negative/generic_call_arity_mismatch.weft" "type error: arity mismatch"
check_rejects "generic_call_non_generic_function" "test/negative/generic_call_non_generic_function.weft" "type error: generic call target is not generic"
check_rejects "generic_call_function_value" "test/negative/generic_call_function_value.weft" "type error: generic call target is not generic"
check_rejects "generic_call_non_generic_constructor" "test/negative/generic_call_non_generic_constructor.weft" "type error: generic call target is not generic"
check_rejects "function_value_arity_mismatch" "test/negative/function_value_arity_mismatch.weft" "type error: arity mismatch"
check_rejects "effect_perform_arity_too_few" "test/negative/effect_perform_arity_too_few.weft" "type error: arity mismatch"
check_rejects "effect_perform_arity_too_many" "test/negative/effect_perform_arity_too_many.weft" "type error: arity mismatch"
check_rejects "deferred_with_k_non_deferred" "test/negative/deferred_with_k_non_deferred.weft" "type error: handler continuation requires deferred effect operation"
check_rejects "deferred_k_capture_lambda" "test/negative/deferred_k_capture_lambda.weft" "type error: continuation cannot escape"
check_rejects "deferred_k_escape_value" "test/negative/deferred_k_escape_value.weft" "type error: continuation cannot escape"
check_rejects "deferred_k_multiple_use" "test/negative/deferred_k_multiple_use.weft" "type error: continuation used more than once"
check_rejects "deferred_k_alias_multiple_use" "test/negative/deferred_k_alias_multiple_use.weft" "type error: continuation used more than once"
check_rejects "deferred_k_capture_lambda_body_multiple_use" "test/negative/deferred_k_capture_lambda_body_multiple_use.weft" "type error: continuation used more than once"
check_rejects "deferred_k_capture_lambda_multiple_use" "test/negative/deferred_k_capture_lambda_multiple_use.weft" "type error: continuation used more than once"
check_rejects "deferred_k_alias_capture_lambda" "test/negative/deferred_k_alias_capture_lambda.weft" "type error: continuation cannot escape"
check_rejects "deferred_k_alias_pass_arg" "test/negative/deferred_k_alias_pass_arg.weft" "type error: argument type mismatch"
check_rejects "deferred_k_non_tail" "test/negative/deferred_k_non_tail.weft" "type error: continuation call must be tail position"
check_rejects "deferred_k_loop_non_tail" "test/negative/deferred_k_conditional_non_tail.weft" "type error: continuation call must be tail position"
check_rejects "deferred_k_arity" "test/negative/deferred_k_arity.weft" "type error: arity mismatch"
check_rejects "deferred_k_helper_multiple_use" "test/negative/deferred_k_helper_multiple_use.weft" "type error: continuation used more than once"
check_rejects "continuation_param_multiple_use" "test/negative/continuation_param_multiple_use.weft" "type error: continuation used more than once"
check_rejects "continuation_param_plain_function" "test/negative/continuation_param_plain_function.weft" "type error: argument type mismatch"
check_rejects "continuation_param_return_any" "test/negative/continuation_param_return_any.weft" "type error: continuation cannot escape"
check_rejects "deferred_k_direct_resume" "test/negative/deferred_k_direct_resume.weft" "type error: use continuation binding instead of resume"
check_rejects "deferred_k_intrinsic_store" "test/negative/deferred_k_intrinsic_store.weft" "type error: continuation cannot escape"
check_rejects "deferred_k_record_store" "test/negative/deferred_k_record_store.weft" "type error: continuation cannot escape"
check_rejects "deferred_k_variant_store" "test/negative/deferred_k_variant_store.weft" "type error: continuation cannot escape"
check_rejects "deferred_k_generic_list_store" "test/negative/deferred_k_generic_list_store.weft" "type error: continuation cannot escape"
check_rejects "deferred_k_generic_identity" "test/negative/deferred_k_generic_identity.weft" "type error: continuation cannot escape"
check_rejects "deferred_k_returned_alias_non_tail" "test/negative/deferred_k_returned_alias_non_tail.weft" "type error: continuation call must be tail position"
check_rejects "deferred_k_returned_alias_record_store" "test/negative/deferred_k_returned_alias_record_store.weft" "type error: continuation cannot escape"
check_rejects "deferred_k_returned_alias_multiple_use" "test/negative/deferred_k_returned_alias_multiple_use.weft" "type error: continuation used more than once"
check_rejects "stored_continuation_store_twice" "test/negative/stored_continuation_store_twice.weft" "type error: continuation used more than once"
check_rejects "stored_continuation_use_after_store" "test/negative/stored_continuation_use_after_store.weft" "type error: continuation used more than once"
check_rejects "handler_clause_unknown_op" "test/negative/handler_clause_unknown_op.weft" "type error: unknown effect operation"
check_rejects "handler_clause_effect_mismatch" "test/negative/handler_clause_effect_mismatch.weft" "type error: handler clause effect mismatch"
check_rejects "handler_clause_arity_too_few" "test/negative/handler_clause_arity_too_few.weft" "type error: arity mismatch"
check_rejects "handler_clause_arity_too_many" "test/negative/handler_clause_arity_too_many.weft" "type error: arity mismatch"
check_rejects "handler_clause_param_type_mismatch" "test/negative/handler_clause_param_type_mismatch.weft" "type error: argument type mismatch"
check_rejects "handler_clause_resume_type_mismatch" "test/negative/handler_clause_resume_type_mismatch.weft" "type error: resume type mismatch"
check_rejects "handler_clause_resume_capture_lambda" "test/negative/handler_clause_resume_capture_lambda.weft" "type error: cannot capture resume"
check_rejects "handler_clause_resume_capture_nested_lambda" "test/negative/handler_clause_resume_capture_nested_lambda.weft" "type error: cannot capture resume"
check_rejects "handler_clause_duplicate" "test/negative/handler_clause_duplicate.weft" "type error: duplicate handler clause"
check_rejects "handler_clause_missing_direct" "test/negative/handler_clause_missing_direct.weft" "type error: missing handler clause"
check_rejects "handler_clause_missing_branch" "test/negative/handler_clause_missing_branch.weft" "type error: missing handler clause"
check_rejects "resume_outside_handler" "test/negative/resume_outside_handler.weft" "type error: resume outside handler clause"
check_rejects "resume_outside_handler_lambda" "test/negative/resume_outside_handler_lambda.weft" "type error: resume outside handler clause"
check_rejects "generic_type_payload_mismatch" "test/negative/generic_type_payload_mismatch.weft" "type error: argument type mismatch"
check_rejects "generic_type_return_mismatch" "test/negative/generic_type_return_mismatch.weft" "type error: value does not match let type annotation"
check_rejects "generic_type_constructor_arity" "test/negative/generic_type_constructor_arity.weft" "type error: arity mismatch"
check_rejects "generic_type_arg_count" "test/negative/generic_type_arg_count.weft" "type error: wrong number of type arguments"
check_rejects "generic_type_pattern_payload_mismatch" "test/negative/generic_type_pattern_payload_mismatch.weft" "type error: return type mismatch"

echo ""
echo "=== Negative Summary ==="
echo "$PASS passed, $FAIL failed"
if [ -n "$ERRORS" ]; then
  echo ""
  echo "Failures:"
  echo -e "$ERRORS"
fi
if [ $FAIL -gt 0 ]; then exit 1; fi
